# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, b'Organizer'), (2, b'Idea collector'), (3, b'Gift buyer (online)'), (4, b'Gift buyer (offline)'), (5, b'Gift wrapper')])),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.User')),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='users',
            field=models.ManyToManyField(through='planner.UserRole', to='planner.User'),
        ),
    ]
