# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_presentidea_presentideacomment_presentideaupvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentidea',
            name='party_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.Party'),
        ),
    ]
