# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_presentidea_party_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.User')),
            ],
        ),
    ]
