# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_auto_20170224_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftidea',
            old_name='party_used',
            new_name='party',
        ),
    ]
